repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [ --fix ]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: commitizen
        name: Check commit message
        entry: uv run cz check --allow-abort --commit-msg-file
        stages: [commit-msg]
        language: python
